{% set name = "types-Deprecated" %}
{% set version = "1.3.1.20251101" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') | lower }}-{{ version }}.tar.gz
  sha256: f002d266b73201f46ec6fc712c1f016067ec6cb44357559cdb50c86b010951a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  commands:
    - test -f $SP_DIR/deprecated-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Deprecated
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
