{% set name = "types-Deprecated" %}
{% set version = "1.2.9.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-Deprecated-{{ version }}.tar.gz
  sha256: ef87327adf3e3c4a4c7d8e06e58f6476710d3466ecfb53c49efb080804a70ef3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/deprecated-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Deprecated
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
